// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eussxomitqyumgsuuflq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1c3N4b21pdHF5dW1nc3V1ZmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjAyMzYsImV4cCI6MjA2NDAzNjIzNn0.EHSgrQESkEIHqNkLxSDd43gDAu9TJ7OYmK8i3VQK9VE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);